version: "3.7"

services:
  strv-newsletter:
    init: true
    container_name: strv-newsletter
    build:
      context: .
      target: development
      args:
        PROJECT_ROOT: "/go/src/github.com/jamm3e3333/strv-newsletter"
    ports:
      - "59110:3000"
    depends_on:
      postgres:
        condition: service_healthy
      firebase-emulator:
        condition: service_started
    volumes:
      - ".:/go/src/github.com/jamm3e3333/strv-newsletter/:cached"
    environment:
      # APP
      CONFIG_HTTP_LISTEN_PORT: 3000
      APP_ENV: local
      CONFIG_ALLOW_ORIGINS: "*"
      CONFIG_HTTP_READ_TIMEOUT: 5s
      CONFIG_HTTP_WRITE_TIMEOUT: 15s
      CONFIG_HTTP_SHUTDOWN_TIMEOUT: 30s
      CONFIG_HEALTH_CHECK_TIMEOUT: 5s
      CONFIG_TIMEZONE: Europe/Warsaw
      CONFIG_APP_NAME: strv_newsletter
      CONFIG_HASH_SECRET: B293A7DC884D9

      # JWT
      CONFIG_JWT_SECRET: vf6dXaJMjYI7jkEhq7rH1F28N1vITNju

      # LOGGER
      CONFIG_LOG_LEVEL: debug
      CONFIG_LOG_DEVEL_MODE: true

      # POSTGRESQL
      CONFIG_DATABASE_HOST: postgres
      CONFIG_DATABASE_PORT: 5432
      CONFIG_DATABASE_USER: postgres
      CONFIG_DATABASE_PASSWORD: postgres
      CONFIG_DATABASE_NAME: strv-newsletter
      CONFIG_DATABASE_POOL_MAX_CONN_LIFETIME: 50s
      CONFIG_DATABASE_POOL_MAX_CONN_IDLE_TIME: 50s
      CONFIG_DATABASE_QUERY_TIMEOUT: 30s
      CONFIG_DATABASE_POOL_MAX_CONNS: 100
      CONFIG_DATABASE_POOL_MIN_CONNS: 1
      CONFIG_DATABASE_POOL_HEALTH_CHECK_PERIOD: 5s

      # FIREBASE
      CONFIG_FIREBASE_DATABASE_URL: http://127.0.0.1:9000/?ns=strv-newsletter-go-vala-jakub-vala-local
      CONFIG_FIREBASE_IS_TESTING_MODE: true

      # EMAIL
      CONFIG_UNSUBSCRIBE_URL: http://localhost:59110/v1/newsletter/subscriber/unsubscribe
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health/readiness || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  postgres:
    image: postgis/postgis:15-3.4
    container_name: postgres
    ports:
      - "54320:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: strv-newsletter
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  firebase-emulator:
    image: spine3/firebase-emulator:latest
    container_name: firebase-emulator
    ports:
      - "4000:4000"
      - "9000:9000"
    environment:
      GCP_PROJECT: strv-newsletter-go-vala-jakub-vala-local
      ENABLE_UI: true
      RDB_EMULATOR_PORT: 9000
      UI_EMULATOR_PORT: 4000
      UI_ENABLED: true
    volumes:
      - "./firebase.json:/firebase/firebase.json"
      - "./database.rules.json:/firebase/database.rules.json"
    healthcheck:
      test: ["CMD-SHELL", "wget --server-response --spider http://localhost:4000 2>&1 | grep 'HTTP/1.1 200 OK' || exit 1"]
      interval: 30s
      timeout: 90s
      retries: 5
      start_period: 40s
